In [1]:
import datajoint as dj
import numpy as np
import pymeshfix

In [2]:
ta3p100 = dj.create_virtual_module("ta3p100","microns_ta3p100")

Connecting celiib@10.28.0.34:3306


In [3]:
#create the output file
##write the OFF file for the neuron
import pathlib
def write_Whole_Neuron_Off_file(neuron_ID,vertices=[], triangles=[]):
    #primary_key = dict(segmentation=1, segment_id=segment_id, decimation_ratio=0.35)
    #vertices, triangles = (mesh_Table_35 & primary_key).fetch1('vertices', 'triangles')
    
    num_vertices = (len(vertices))
    num_faces = len(triangles)
    
    #get the current file location
    file_loc = pathlib.Path.cwd() / "temp"
    filename = "neuron_" + str(neuron_ID)
    path_and_filename = file_loc / filename
    
    #print(file_loc)
    #print(path_and_filename)
    
    #open the file and start writing to it    
    f = open(str(path_and_filename) + ".off", "w")
    f.write("OFF\n")
    f.write(str(num_vertices) + " " + str(num_faces) + " 0\n" )
    
    
    #iterate through and write all of the vertices in the file
    for verts in vertices:
        f.write(str(verts[0]) + " " + str(verts[1]) + " " + str(verts[2])+"\n")
    
    #print("Done writing verts")
        
    for faces in triangles:
        f.write("3 " + str(faces[0]) + " " + str(faces[1]) + " " + str(faces[2])+"\n")
    
    print("Done writing OFF file")
    #f.write("end")
    
    return str(path_and_filename),str(filename),str(file_loc)

In [4]:
ta3p100.Decimation35() & "segmentation=2"

*segmentation  *segment_id    *decimation_ra n_vertices     n_triangles    vertices   triangles 
+------------+ +------------+ +------------+ +------------+ +------------+ +--------+ +--------+
2              64851834634136 0.35           338990         673206         =BLOB=     =BLOB=    
2              64851834634137 0.35           234848         460727         =BLOB=     =BLOB=    
2              64851834634137 0.35           2267151        4510325        =BLOB=     =BLOB=    
2              64851834634138 0.35           533632         1063782        =BLOB=     =BLOB=    
2              64851834634138 0.35           176358         351867         =BLOB=     =BLOB=    
2              64851834634138 0.35           2792025        5523545        =BLOB=     =BLOB=    
2              64851834634138 0.35           185381         364564         =BLOB=     =BLOB=    
   ...
 (396 tuples)

In [5]:
segment_id = 648518346349504955

In [6]:
new_dict=dict(segmentation=2,segment_id=segment_id)
vertices_ar,triangles_ar = (ta3p100.Decimation35 & new_dict).fetch("vertices","triangles")
vertices_ar

array([array([[180964.4375   , 244257.578125 ,  50500.890625 ],
       [180957.765625 , 244271.671875 ,  50415.3359375],
       [181140.953125 , 244111.4375   ,  50475.5234375],
       ...,
       [464124.4375   , 256514.703125 ,  69246.0703125],
       [464071.34375  , 256388.6875   ,  69154.0078125],
       [464128.34375  , 256495.421875 ,  69117.625    ]])], dtype=object)

In [7]:
vertices = vertices_ar[0]
triangles = triangles_ar[0]
print(triangles)

[[562316 562273 562187]
 [562316 562187 562246]
 [562288 562316 562246]
 ...
 [559092 558964 558947]
 [558914 558807 558843]
 [558413 558397 558387]]


In [ ]:
#write the whole mesh original as off file for visualization purposes
write_Whole_Neuron_Off_file(str(segment_id)+"_orig",vertices,triangles)

In [ ]:
# #PYMESH METHOD FOR GENERATING THE WATER-TIGHT/NON-MANIFOLD MESH
# import time
# start_time = time.time()
# meshfix = pymeshfix.MeshFix(vertices,triangles)
# meshfix.repair()
# vertices_new = meshfix.v
# faces_new = meshfix.f
# write_Whole_Neuron_Off_file(str(segment_id) + "_pymeshfix",vertices_new,faces_new)
# print(f"Pymeshfix shrinkwrap took {time.time()-start_time} seconds")

In [ ]:
# #PYMESH METHOD FOR GENERATING THE WATER-TIGHT/NON-MANIFOLD MESH
# pymesh_type = "_pymeshfix_jT_rF"
# joincomp_setting = True
# remove_smallest_components_setting = False


# import time
# start_time = time.time()
# meshfix = pymeshfix.MeshFix(vertices,triangles)
# meshfix.repair(verbose=False
#                ,joincomp=joincomp_setting
#                ,remove_smallest_components=remove_smallest_components_setting)
# vertices_new = meshfix.v
# faces_new = meshfix.f
# write_Whole_Neuron_Off_file(str(segment_id) + pymesh_type,vertices_new,faces_new)
# print(f"Pymeshfix {pymesh_type} shrinkwrap took {time.time()-start_time} seconds")


In [ ]:
help(pymeshfix.MeshFix.repair)

In [ ]:
# #creates the skeleton for mesh from pymeshfix
# import time
# start_time = time.time()
# import calcification_Module as cm
# cm.calcification("temp/neuron_"+str(segment_id)+pymesh_type)
# print(f"Pymeshfix {pymesh_type} skeletonization took {time.time()-start_time} seconds")



In [ ]:
#PYMESH METHOD FOR GENERATING THE WATER-TIGHT/NON-MANIFOLD MESH
pymesh_type = "_pymeshfix_jT_rT"
joincomp_setting = True
remove_smallest_components_setting = True


import time
start_time = time.time()
meshfix = pymeshfix.MeshFix(vertices,triangles)
meshfix.repair(verbose=False
               ,joincomp=joincomp_setting
               ,remove_smallest_components=remove_smallest_components_setting)
vertices_new = meshfix.v
faces_new = meshfix.f
write_Whole_Neuron_Off_file(str(segment_id) + pymesh_type,vertices_new,faces_new)
print(f"Pymeshfix {pymesh_type} shrinkwrap took {time.time()-start_time} seconds")


In [ ]:
#creates the skeleton for mesh from pymeshfix
import time
start_time = time.time()
import calcification_Module as cm
cm.calcification("temp/neuron_"+str(segment_id)+pymesh_type)
print(f"Pymeshfix {pymesh_type} skeletonization took {time.time()-start_time} seconds")



In [ ]:
#PYMESH METHOD FOR GENERATING THE WATER-TIGHT/NON-MANIFOLD MESH
pymesh_type = "_pymeshfix_jF_rF"
joincomp_setting = False
remove_smallest_components_setting = False


import time
start_time = time.time()
meshfix = pymeshfix.MeshFix(vertices,triangles)
meshfix.repair(verbose=False
               ,joincomp=joincomp_setting
               ,remove_smallest_components=remove_smallest_components_setting)
vertices_new = meshfix.v
faces_new = meshfix.f
write_Whole_Neuron_Off_file(str(segment_id) + pymesh_type,vertices_new,faces_new)
print(f"Pymeshfix {pymesh_type} shrinkwrap took {time.time()-start_time} seconds")


In [ ]:
#creates the skeleton for mesh from pymeshfix
import time
start_time = time.time()
import calcification_Module as cm
cm.calcification("temp/neuron_"+str(segment_id)+pymesh_type)
print(f"Pymeshfix {pymesh_type} skeletonization took {time.time()-start_time} seconds")



In [ ]:
#PYMESH METHOD FOR GENERATING THE WATER-TIGHT/NON-MANIFOLD MESH
pymesh_type = "_pymeshfix_jF_rT"
joincomp_setting = False
remove_smallest_components_setting = True


import time
start_time = time.time()
meshfix = pymeshfix.MeshFix(vertices,triangles)
meshfix.repair(verbose=False
               ,joincomp=joincomp_setting
               ,remove_smallest_components=remove_smallest_components_setting)
vertices_new = meshfix.v
faces_new = meshfix.f
write_Whole_Neuron_Off_file(str(segment_id) + pymesh_type,vertices_new,faces_new)
print(f"Pymeshfix {pymesh_type} shrinkwrap took {time.time()-start_time} seconds")



In [ ]:
#creates the skeleton for mesh from pymeshfix
import time
start_time = time.time()
import calcification_Module as cm
cm.calcification("temp/neuron_"+str(segment_id)+pymesh_type)
print(f"Pymeshfix {pymesh_type} skeletonization took {time.time()-start_time} seconds")