In [6]:
import gdist
from meshparty import trimesh_io

In [2]:
dir(gdist)

['__builtins__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__test__',
 'compute_gdist',
 'local_gdist_matrix',
 'numpy',
 'scipy']

In [4]:
help(gdist.compute_gdist)

Help on built-in function compute_gdist in module gdist:

compute_gdist(...)
    This is the wrapper function for computing geodesic distance between a set 
    of sources and targets on a mesh surface. This function accepts five 
    arguments:
        ``vertices``: defines x,y,z coordinates of the mesh's vertices.
        ``triangles``: defines faces of the mesh as index triplets into vertices.
        ``source_indices``: Index of the source on the mesh.
        ``target_indices``: Index of the targets on the mesh.
        ``max_distance``: 
    and returns a numpy.ndarray((len(target_indices), ), dtype=numpy.float64) 
    specifying the shortest distance to the target vertices from the nearest 
    source vertex on the mesh. If no target_indices are provided, all vertices 
    of the mesh are considered as targets, however, in this case, specifying 
    max_distance will limit the targets to those vertices within max_distance of
    a source.
    
    NOTE: This is the function to u

In [33]:
dir(trimesh_io.trimesh.load_mesh)
help(trimesh_io.trimesh.load_mesh)

Help on function load_mesh in module trimesh.constants:

load_mesh(*args, **kwargs)
    Load a mesh file into a Trimesh object
    
    Parameters
    -----------
    file_obj : str or file object
      File name or file with mesh data
    file_type : str or None
      Which file type, e.g. 'stl'
    kwargs : dict
      Passed to Trimesh constructor
    
    Returns
    ----------
    mesh : trimesh.Trimesh or trimesh.Scene
      Loaded geometry data



In [35]:
mesh = trimesh_io.trimesh.load_mesh(file_obj="scaled_clean.off",file_type="off")

In [48]:
dir(mesh.bounding_primitive)
#mesh.bounding_primitive.export("bbox.off","off") //prints out the bounding box
#mesh.bounding_primitive.faces
#mesh.bounding_primitive.edges
mesh.bounding_primitive.vertices

#one side of the face:
#[1, 3, 0],[4, 1, 0]

TrackedArray([[355687.86152617, 186147.57560177,  11177.87865536],
              [353948.5314709 , 198247.77058017,  33980.29091918],
              [331642.35256989, 189326.24571134,   7656.95272915],
              [329903.02251462, 201426.44068974,  30459.36499297],
              [359307.97140907, 203587.34592889,   2199.5278982 ],
              [357568.6413538 , 215687.54090729,  25001.94016202],
              [335262.46245279, 206766.01603846,  -1321.398028  ],
              [333523.13239752, 218866.21101685,  21481.01423581]])

In [50]:
dir(mesh.bounding_box)

['__abstractmethods__',
 '__add__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_cache',
 '_center_mass',
 '_create_mesh',
 '_data',
 '_density',
 '_kwargs',
 '_validate',
 '_visual',
 'apply_obb',
 'apply_scale',
 'apply_transform',
 'apply_translation',
 'area',
 'area_faces',
 'body_count',
 'bounding_box',
 'bounding_box_oriented',
 'bounding_cylinder',
 'bounding_primitive',
 'bounding_sphere',
 'bounds',
 'center_mass',
 'centroid',
 'compute_stable_poses',
 'contains',
 'convert_units',
 'convex_decomposition',
 'convex_hull',
 'copy',
 'crc',
 'density',
 'difference',

In [52]:
##result of gdist this should be between dijkstras and 3D distance

import numpy
#temp = numpy.loadtxt("flat_triangular_mesh.txt", skiprows=1)
#vertices = temp[0:121].astype(numpy.float64)
#triangles = temp[121:321].astype(numpy.int32)

mesh = trimesh_io.read_mesh("scaled_clean.obj")
vertices = mesh[0].astype(numpy.float64)
triangles = mesh[1].astype(numpy.int32)

#index of the source
src = numpy.array([1], dtype=numpy.int32)
#index of the target
trg = numpy.array([100], dtype=numpy.int32)

print(type(vertices[1][0]))
print(type(triangles[1][0]))
print(type(src[0]))
print(type(trg[0]))


#array([ 0.2])

<class 'numpy.float64'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
CPU times: user 5.07 s, sys: 136 ms, total: 5.2 s
Wall time: 5.35 s


In [53]:
%time myArray = gdist.compute_gdist(vertices, triangles, source_indices = src, target_indices = trg)

CPU times: user 5.36 s, sys: 160 ms, total: 5.52 s
Wall time: 5.55 s


In [25]:
myArray

array([2445.6989367])

In [28]:
import math
import numpy as np
from collections import Counter

def calculate_distance(p1,p2):
    distance = math.sqrt((p1[0]-p2[0])**2 + (p1[1]-p2[1])**2 + (p1[2]-p2[2])**2)
    return distance

In [29]:
#get 3D distance
src = 1
target = 100
src_vert = vertices[src]
target_vert = vertices[target]

print(calculate_distance(src_vert,target_vert))
#checks out and is always longer than gdist

2419.1169583603905


In [ ]:
#find the dijkstra's path

In [16]:
print(mesh[1])

[[    1     7     0]
 [    3     8     2]
 [    9     7     1]
 ...
 [85502 85538 85532]
 [85532 85538 85401]
 [85401 85538 85395]]


In [ ]:
#test absolute distance 