In [5]:
import datajoint as dj
import numpy as np
import pymeshfix

In [6]:
ta3p100 = dj.create_virtual_module("ta3p100","microns_ta3p100")

In [7]:
segment_id = 648518346349504955
new_dict=dict(segmentation=2,segment_id=segment_id)
vertices_ar,triangles_ar = (ta3p100.Decimation35 & new_dict).fetch("vertices","triangles")

vertices = vertices_ar[0]
triangles = triangles_ar[0]
print(triangles)

[[562316 562273 562187]
 [562316 562187 562246]
 [562288 562316 562246]
 ...
 [559092 558964 558947]
 [558914 558807 558843]
 [558413 558397 558387]]


In [8]:
from meshparty import trimesh_io
mesh = trimesh_io.Mesh(vertices=vertices, faces=triangles)
voxels = mesh.voxelized(500)
voxel_mesh = voxels.as_boxes()

In [10]:
dir(voxel_mesh)

['__abstractmethods__',
 '__add__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_cache',
 '_center_mass',
 '_data',
 '_density',
 '_kwargs',
 '_validate',
 '_visual',
 'apply_obb',
 'apply_scale',
 'apply_transform',
 'apply_translation',
 'area',
 'area_faces',
 'body_count',
 'bounding_box',
 'bounding_box_oriented',
 'bounding_cylinder',
 'bounding_primitive',
 'bounding_sphere',
 'bounds',
 'center_mass',
 'centroid',
 'compute_stable_poses',
 'contains',
 'convert_units',
 'convex_decomposition',
 'convex_hull',
 'copy',
 'crc',
 'density',
 'difference',
 'edges',
 'edge