In [60]:
import datajoint as dj
import numpy as np
import trimesh

m65 = dj.create_virtual_module('m65', 'microns_minnie65_01')
schema = dj.schema("microns_minnie65_01")

/usr/local/lib/python3.6/dist-packages/datajoint/connection.py:215: UserWarning: MySQL server has gone away. Reconnecting to the server.
  warnings.warn("MySQL server has gone away. Reconnecting to the server.")


In [3]:
segment_id = 107816118160698192
version = 0
lookup_key = dict(segment_id=segment_id, version = version)

In [4]:
subsegments = (m65.FromNeuromancer.Subsegment & lookup_key).fetch(as_dict=True)
subsegments_ids = [(k["subsegment_id"],k["version"]) for k in subsegments]
subsegments_ids

[(101902395407434514, 0),
 (102887695332199785, 0),
 (102889619544428494, 0),
 (102890719257233540, 0),
 (103029257454175365, 0),
 (103029738490480020, 0),
 (103242493990490048, 0),
 (103313137746848709, 0),
 (103665737381631891, 0),
 (103733425932104471, 0),
 (103870246544622156, 0),
 (104508237898222004, 0),
 (104859394290245283, 0),
 (105144579648752618, 0),
 (105846205908604595, 0),
 (105849023474493209, 0),
 (106060060920826917, 0),
 (106130429664994368, 0),
 (106130429665017025, 0),
 (106341673403199619, 0),
 (106412042080209043, 0),
 (106412042080341017, 0),
 (106412042147252306, 0),
 (106482410824372053, 0),
 (106626240554902577, 0),
 (106766771884709652, 0),
 (106837071909413349, 0),
 (107186991485053514, 0),
 (107324842621243460, 0),
 (107395073859688816, 0),
 (107395073926335964, 0),
 (107465442603440385, 0),
 (107466611170176807, 0),
 (107471215173990840, 0),
 (107606317463760247, 0),
 (107608035651997587, 0),
 (107608379182540920, 0),
 (107817423629214654, 0),
 (1078175610

In [9]:
import pandas as pd
def retrieve1(core_segment_id, version=-1):
        #print("core_segment_id = " + str(core_segment_id))
        #print("version = " + str(version))
        rel = m65.FromNeuromancerMergeError & dict(segment_id=core_segment_id)
        if version == -1:
            rel &= dj.U('segment_id').aggr(rel.proj(), version='max(version)')
        else:
            rel &= dict(version=version)

        if len(rel) == 1:
            csv_string = rel.fetch1('annotations').item()
            
            from io import StringIO
            
            with StringIO(csv_string) as csv_io:
                ano_df = pd.read_csv(csv_io)
            return ano_df
        else:
            return None

In [10]:
df = retrieve1(segment_id,version)

In [16]:
len(df)

46

In [50]:
line_data = df[df["type"] != "point"][["pointA","pointB"]].to_numpy()
import ast
converted_line_array = np.array([ast.literal_eval(p) for p in line_data.ravel()]).reshape(-1,2,3)
for a,b in converted_line_array:
    #can call the create function from here
    print(a)
    print(b)
    print("-------")

[327247.375      178985.515625    19584.38671875]
[327222.71875    179089.828125    19592.59179688]
-------
[327247.375      178985.515625    19584.38867188]
[327305.21875    178818.8125      19586.00585938]
-------
[326267.75       179445.125       19561.33789062]
[326277.25       179483.46875     19555.34179688]
-------
[329314.875      177256.8125      19561.66992188]
[329424.34375    177266.328125    19552.02929688]
-------
[293157.375      174134.96875     27141.63867188]
[293066.28125  173823.984375  27137.859375]
-------
[293296.875      171229.765625    27434.18554688]
[293248.6875     171141.90625     27447.89648438]
-------
[293304.21875  171219.859375  27435.109375]
[293336.1875     171158.140625    27440.80078125]
-------
[288868.40625    165342.828125    26353.61328125]
[288644.71875    165439.4375      26357.63476562]
-------
[288879.0625     165335.28125     26353.48828125]
[289062.125      165178.046875    26337.56640625]
-------


In [51]:
df[df["type"] != "point"]

point  type                                        id tagIds description  \
37   NaN  line  e8cdfd24dfa72f3e644fc481644b6cbde497241e     []         NaN   
38   NaN  line  6de92191b629d59869c2f10160fcb608337a34e4     []         NaN   
39   NaN  line  2530e8f1151f1073e8b1533e73cfa1e315c11030     []         NaN   
40   NaN  line  c5546cc6fb72be1268741726770e6353805c9402     []         NaN   
41   NaN  line  11abdfba8a33662666bc31fe5abd89e40cf6b43d     []         NaN   
42   NaN  line  2dec5edc57e5ba4403f27c6bbcdf2e939c4200ae     []         NaN   
43   NaN  line  5d912febb289938d9fc741e56106a7f6984089fa     []         NaN   
44   NaN  line  455d7c04bb0058d5bf4df40f93337cdb3bcd3b0e     []         NaN   
45   NaN  line  e79411eed321500b4bd8423d9b44b7d64c88a522     []         NaN   

                                           pointA  \
37    [327247.375, 178985.515625, 19584.38671875]   
38   [327247.375, 178985.515625, 19584.388671875]   
39       [326267.75, 179445.125, 19561.337890625]   
40     [329314.875, 177256.8125, 19561.669921875]   
41    [293157.375, 174134.96875, 27141.638671875]   
42   [293296.875, 171229.765625, 27434.185546875]   
43    [293304.21875, 171219.859375, 27435.109375]   
44  [288868.40625, 165342.828125, 26353.61328125]   
45    [288879.0625, 165335.28125, 26353.48828125]   

                                            pointB  
37  [327222.71875, 179089.828125, 19592.591796875]  
38    [327305.21875, 178818.8125, 19586.005859375]  
39      [326277.25, 179483.46875, 19555.341796875]  
40  [329424.34375, 177266.328125, 19552.029296875]  
41     [293066.28125, 173823.984375, 27137.859375]  
42    [293248.6875, 171141.90625, 27447.896484375]  
43    [293336.1875, 171158.140625, 27440.80078125]  
44    [288644.71875, 165439.4375, 26357.634765625]  
45     [289062.125, 165178.046875, 26337.56640625]

In [46]:
points_data = df[df["type"] == "point"][["point"]].to_numpy()
import ast
converted_point_array = np.array([ast.literal_eval(p) for p in points_data.ravel()]).reshape(-1,3)
for a in converted_point_array:
    #can call the create function from here
    print(a)
    print("------")

[322834.71875    201205.578125    21575.34570312]
------
[322617.78125    202976.359375    21605.45898438]
------
[317596.5625    216555.59375    22067.7109375]
------
[296195.65625    198233.3125      27718.27148438]
------
[296214.46875    198622.78125     27711.29101562]
------
[296134.59375    200622.484375    27823.16015625]
------
[322637.40625    203027.828125    21607.18359375]
------
[324405.0625     180384.0625      21971.38085938]
------
[325020.1875     178394.71875     21964.11914062]
------
[325447.25       177643.640625    21967.45898438]
------
[321273.96875    195312.046875    21433.50585938]
------
[321125.9375     194999.609375    21404.21289062]
------
[325900.46875    197990.65625     21696.30273438]
------
[322814.90625    200698.234375    21547.73632812]
------
[327531.625      202850.8125      20970.51367188]
------
[324618.6875   199613.046875  21112.140625]
------
[324560.5      201157.078125  21115.71875 ]
------
[322704.46875    203295.96875     21608.552734

In [43]:
df[df["type"] == "point"]

point   type  \
0   [322834.71875, 201205.578125, 21575.345703125]  point   
1   [322617.78125, 202976.359375, 21605.458984375]  point   
2       [317596.5625, 216555.59375, 22067.7109375]  point   
3     [296195.65625, 198233.3125, 27718.271484375]  point   
4    [296214.46875, 198622.78125, 27711.291015625]  point   
5    [296134.59375, 200622.484375, 27823.16015625]  point   
6    [322637.40625, 203027.828125, 21607.18359375]  point   
7      [324405.0625, 180384.0625, 21971.380859375]  point   
8     [325020.1875, 178394.71875, 21964.119140625]  point   
9      [325447.25, 177643.640625, 21967.458984375]  point   
10  [321273.96875, 195312.046875, 21433.505859375]  point   
11   [321125.9375, 194999.609375, 21404.212890625]  point   
12   [325900.46875, 197990.65625, 21696.302734375]  point   
13  [322814.90625, 200698.234375, 21547.736328125]  point   
14      [327531.625, 202850.8125, 20970.513671875]  point   
15      [324618.6875, 199613.046875, 21112.140625]  point   
16          [324560.5, 201157.078125, 21115.71875]  point   
17   [322704.46875, 203295.96875, 21608.552734375]  point   
18      [322604.25, 203090.96875, 21605.314453125]  point   
19      [322803.46875, 208804.96875, 21650.953125]  point   
20   [322847.09375, 200718.171875, 21520.94921875]  point   
21     [322861.09375, 198811.375, 21579.333984375]  point   
22       [322745.4375, 206075.40625, 21616.203125]  point   
23        [322868.4375, 200745.484375, 21547.4375]  point   
24   [329715.1875, 204130.609375, 20733.490234375]  point   
25    [319950.3125, 202678.109375, 22100.12109375]  point   
26   [319858.3125, 202965.703125, 22108.357421875]  point   
27  [313818.15625, 196660.234375, 23158.189453125]  point   
28  [322992.40625, 217139.984375, 21820.412109375]  point   
29   [321320.8125, 219176.640625, 21802.607421875]  point   
30     [317629.15625, 216904.421875, 21965.328125]  point   
31     [316459.53125, 216729.375, 22076.896484375]  point   
32     [317514.71875, 216157.0625, 22102.05078125]  point   
33   [317367.1875, 216634.046875, 22081.033203125]  point   
34     [327603.65625, 218588.34375, 22044.5859375]  point   
35     [333960.25, 191201.328125, 23849.560546875]  point   
36  [321282.15625, 195309.234375, 21440.216796875]  point   

                                          id tagIds  \
0   6c479ab5de29de5e548050f0967676751b186a67     []   
1   224a7db7f6a3b211570f3ab22e048019f7f2b934     []   
2   a489bccc51df6cf98ed139e6bf0c0a89ed159ae0     []   
3   00988e1f7951bf0f2b1c366eeae1f3defca7c882     []   
4   23c18569477a5f3cb069ec79c9335056fbeee2a6     []   
5   1558e73e680294870b4d5ff97a7d4e81ad886cd2     []   
6   e609ee0fb9249d2cf3bc8985d35d92b0e8db113b     []   
7   ba5e222d6e809cb56f4fd7641576a9c052fc50da     []   
8   17751ed026ae9ea48b9c12b415a3fd3ced3dc536     []   
9   badaf06400fcda0c018cfa443f48d458dd71256f     []   
10  2eb93f418042e57b5733ff1cb4767ac5626a3f20     []   
11  17fc9e7b8dbfa25a2988ce931d8ddd803d88b8c8     []   
12  c2c70f2676a887d07a57160f52f2d24d86ca8599     []   
13  3bd93972279bbb1c64c3f769ca3cafc81918a7aa     []   
14  3abf5667d1a41a654ac025c1228e0bea4115a79d     []   
15  e2fdabe57d36177a9a1ee23ee98480e0b8970826     []   
16  ada20f22ceaecea2578fae57df6eb377a91b15f0     []   
17  2e9bd2e393f75ac3e4dd83a3dfa186c23eb35322     []   
18  bac1c1217664ec3eb301f9f74be876ae51dac9cb     []   
19  6bac126383ae7907e1fe05caa78940106f1ae649     []   
20  ed6e39acb5734fe85a4535ca8b675fb4df290a33     []   
21  0ac60f5765cccf4f255d17d0700707dd48bf850b     []   
22  37b03fee0164e0df64b9a25a9ad079fc5065517c     []   
23  3f5c53c4918212d627c1e2cad7c05ea93f27abbe     []   
24  d3b39b5388501af5f58a0495c65bb966b76cfbed     []   
25  99d823ac2234f4ecc9722ca155d2ae61bf1a7c82     []   
26  6d887183a75018c9fd7de21a766062c7ac8cefe5     []   
27  1ba889dd45d40cdef950c2f883417fe50ae4d2ea     []   
28  ce35451fa3620f923de7a0701233dde5f7d04548     []   
29  a79756a673737c6b28ea561bec124d8486cee027     []   
30  a802cc4bdf2c8e8b7

In [ ]:
# How to create the points and the lines: 
# box maker function
def create_synapse_box(center,side_length):
    """
    Purpose: Will create the mesh variables of vertices and faces
    for a box with a specified center and side length
    
    Parameters:
    center (tuple/np.array) : list of the x,y,z coordinates of the box
    side_length(float)      : the length that the sides need to be of box
    
    Returns: 
    mesh_vertices (np.array) : np array store the vertices as rows and the elements as the coordinates for the box
    mesh_faces (np.array) : np array store the faces as rows and the elements as the referenced vertices for the box
    
    How to use function: 
    create_synapse_box((2,2,2),2.5)
    """
    
    unit_box_vertices = np.array([
        [0,0,0],
        [1,0,0],
        [1,1,0],
        [0,1,0],
        [0,0,1],
        [1,0,1],
        [1,1,1],
        [0,1,1],
    ])

    unit_box_faces = np.array([
        [0,4,5],
        [0,5,1],
        [1,5,6],
        [1,6,2],
        [2,6,7],
        [2,7,3],
        [3,7,4],
        [3,4,0],
        [5,4,7],
        [6,5,7],
        [1,2,0],
        [3,0,2]

        ])

    #Now need to shift it down to center
    unit_box_vertices = unit_box_vertices - 0.5
    
    unit_box_vertices = unit_box_vertices*side_length
    unit_box_vertices = unit_box_vertices + np.array(center)
    
    return unit_box_vertices,unit_box_faces



In [49]:
face_vertices_a = np.array([
        [0,1,1],
        [0,1,-1],
        [0,-1,1],
        [0,-1,-1]
    ])

print("a = " + str(a))
face_vertices_a + a
    


a = [321282.15625    195309.234375    21440.21679688]


array([[321282.15625   , 195310.234375  ,  21441.21679688],
       [321282.15625   , 195310.234375  ,  21439.21679688],
       [321282.15625   , 195308.234375  ,  21441.21679688],
       [321282.15625   , 195308.234375  ,  21439.21679688]])

In [52]:
center_a = np.array(a)
center_b = np.array(b)

face_vertices_a = np.array([
    [0,1,1],
    [0,1,-1],
    [0,-1,1],
    [0,-1,-1]
])

face_vertices_b = face_vertices_a.copy()


#apply the necessary rotation (skipping for now)

#add shift the face vertices to the correct center points
shifted_face_vertices_a =  face_vertices_a + center_a
shifted_face_vertices_b = face_vertices_b + center_b

#stack 


In [57]:
shifted_face_vertices_b

array([[289062.125     , 165179.046875  ,  26338.56640625],
       [289062.125     , 165179.046875  ,  26336.56640625],
       [289062.125     , 165177.046875  ,  26338.56640625],
       [289062.125     , 165177.046875  ,  26336.56640625]])

In [56]:
np.vstack([shifted_face_vertices_a,shifted_face_vertices_b])

array([[288879.0625    , 165336.28125   ,  26354.48828125],
       [288879.0625    , 165336.28125   ,  26352.48828125],
       [288879.0625    , 165334.28125   ,  26354.48828125],
       [288879.0625    , 165334.28125   ,  26352.48828125],
       [289062.125     , 165179.046875  ,  26338.56640625],
       [289062.125     , 165179.046875  ,  26336.56640625],
       [289062.125     , 165177.046875  ,  26338.56640625],
       [289062.125     , 165177.046875  ,  26336.56640625]])

In [112]:
x = np.array([1,3,5])
x.reshape(-1,)

array([1, 3, 5])

In [144]:
# How to create the points and the lines: 
# box maker function

def calculate_normal_vector(p1,p2,p3):
    A = p2 - p1
    A = A/np.linalg.norm(A)
    B = p3 - p1
    B = B/np.linalg.norm(B)
    
    print("A.shape = " + str(A.shape))
    print("B.shape = " + str(B.shape))

    normal = np.cross(A,B)
    normal = normal/np.linalg.norm(normal)
    return normal

#now need to find the rotation needed
def rotation_vp3(a,b):
    a = a/np.linalg.norm(a)
    b = b/np.linalg.norm(b)
    

    
    if np.dot(a,b) == 1 or np.dot(a,b) == -1:
        return np.identity(len(a))
    
    print("a.shape = " + str(a.shape))
    print("b.shape = " + str(b.shape))
    
    v = np.cross(a,b)
    print("v = " + str(v))
    s = np.linalg.norm(v)
    c = np.dot(a,b)
    
    v_matrix = np.array([
        [0, -v[2] , v[1]],
        [v[2], 0, -v[0]],
        [-v[1], v[0], 0]
    ])
    
    v_matrix_squared = v_matrix @ v_matrix
    
    R = np.identity(len(a)) + v_matrix + v_matrix_squared * (1/(1+c))
    
    return R


def create_annotation_line(center_a,center_b,side_length):
    """
    Purpose: Will create the mesh variables of vertices and faces
    for a box with a specified center and side length
    
    Parameters:
    center (tuple/np.array) : list of the x,y,z coordinates of the box
    side_length(float)      : the length that the sides need to be of box
    
    Returns: 
    mesh_vertices (np.array) : np array store the vertices as rows and the elements as the coordinates for the box
    mesh_faces (np.array) : np array store the faces as rows and the elements as the referenced vertices for the box
    
    How to use function: 
    create_synapse_box((2,2,2),2.5)
    """
    center_a = np.array(center_a)
    center_b = np.array(center_b)
    

    face_vertices_a = np.array([
        [0,1,1],
        [0,1,-1],
        [0,-1,1],
        [0,-1,-1]
    ])
    
    
    #Now need to shift it down to center
    face_vertices_a = face_vertices_a*side_length
    
    #apply the necessary rotation (skipping for now)
    direction_of_line = center_b - center_a
    direction_of_line = direction_of_line/np.linalg.norm(direction_of_line)
    print("direction_of_line = " + str(direction_of_line))
    print("direction_of_line = " + str(direction_of_line.shape))
    
    # normal vector is just the cross product of 2 lines on the traingle (ALWAYS STAYS SAME NORMAL AT BEGINNING)
    p1 = np.array([0,1,1])
    p2 = np.array([0,1,-1])
    p3 = np.array([0,-1,1])
    
    normal = calculate_normal_vector(p1,p2,p3)

    print("normal = " + str(normal.shape))
    print("normal = " + str(normal))

    rotation_matrix_for_normal = rotation_vp3(normal,direction_of_line)
    
    #rotate the points and then calculate rotation matrix 
    face_vertices_a = (rotation_matrix_for_normal @ face_vertices_a.T).T
    #face_vertices_b = rotation_matrix_for_normal @ face_vertices_b.T
    face_vertices_b = face_vertices_a.copy()
    

    #verify that both the faces have the normals that are in same direction as beginning line
    rotated_normal_a = calculate_normal_vector(face_vertices_a[0].reshape(-1,),face_vertices_a[1].reshape(-1,),face_vertices_a[2].reshape(-1,))
    print("np.dot(rotated_normal_a,direction_of_line) = " + str(np.dot(rotated_normal_a,direction_of_line)))
    #rotated_normal_b = calculate_normal_vector(face_vertices_b[0],face_vertices_b[1],face_vertices_b[2])
    #print("np.dot(rotated_normal_b,direction_of_line) = " + str(np.dot(rotated_normal_b,direction_of_line)))
    
    
    line_faces = np.array([
        [1,2,3],
        [2,3,4],
        [5,6,7],
        [6,7,8],
        [5,1,7],
        [1,3,7],
        [6,8,2],
        [2,8,4],
        [6,2,5],
        [2,1,5],
        [8,7,4],
        [4,7,3]
    ])
    
    line_faces = line_faces - 1 #makes all the vertices 0 indexed

    
    
    #add shift the face vertices to the correct center points
    shifted_face_vertices_a =  face_vertices_a + center_a
    shifted_face_vertices_b = face_vertices_b + center_b
    
    #stack into final vertices list 
    line_vertices = np.vstack([shifted_face_vertices_a,shifted_face_vertices_b])
    
    
    return line_vertices,line_faces



In [145]:
a = np.array([0,0,0])
b = np.array([0,0,1])
side_length = 0.5

line_vertices,line_faces = create_annotation_line(a,b,side_length)
line_mesh = trimesh.Trimesh(vertices=line_vertices,faces=line_faces)
line_mesh.show()

direction_of_line = [0. 0. 1.]
direction_of_line = (3,)
A.shape = (3,)
B.shape = (3,)
normal = (3,)
normal = [-1. -0. -0.]
a.shape = (3,)
b.shape = (3,)
v = [0. 1. 0.]
A.shape = (3,)
B.shape = (3,)
np.dot(rotated_normal_a,direction_of_line) = 1.0


/usr/local/lib/python3.6/dist-packages/IPython/core/display.py:701: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")


In [ ]:
#calculate the normal vectors
#calculate the rotation matrix: https://math.stackexchange.com/questions/180418/calculate-rotation-matrix-to-align-vector-a-to-vector-b-in-3d


In [73]:
x = np.array([1,3,4])
np.dot(x,x)
print(np.dot(x,2))
np.cross(x,x)

[2 6 8]


array([0, 0, 0])

In [77]:
np.linalg.norm(x/np.linalg.norm(x))

1.0

In [92]:
### MATLAB FUNCTION ON HOW TO FIND ROTATION MATRIX
# https://math.stackexchange.com/questions/180418/calculate-rotation-matrix-to-align-vector-a-to-vector-b-in-3d 
# function v = reflection( u, n )     % Reflection of u on hyperplane n.
# %
# % u can be a matrix. u and v must have the same number of rows.

# v = u - 2 * n * (n'*u) / (n'*n);

# return

# u = a/norm(a);                      % a and b must be column vectors
# v = b/norm(b);                      % of equal length
# N = length(u);
# S = reflection( eye(N), v+u );      % S*u = -v, S*v = -u 
# R = reflection( S, v );             % v = R*u

def reflection(u,n):
    print("(n.T @ n) = " + str((n.T @ n)))
    print("(n.T @ u) / (n.T @ n) = " + str((n.T @ u) / (n.T @ n)))
    return u - 2*n*(n.T @ u) / (n.T @ n)
def find_rotation_matrix(a,b):
    u = a/np.linalg.norm(a)
    v = b/np.linalg.norm(b)
    N = len(u)
    S = reflection(np.identity(N), v + u)
    R = reflection(S,v)
    return R

a = np.array([1,1,1])
a = a/np.linalg.norm(a)
b = np.array([0,0,1])

R = find_rotation_matrix(a,b)
R @ a

(n.T @ n) = 3.154700538379252
(n.T @ u) / (n.T @ n) = [0.1830127 0.1830127 0.5      ]
(n.T @ n) = 1.0
(n.T @ u) / (n.T @ n) = [-0.21132487 -0.21132487 -0.57735027]


array([0.0893164, 0.0893164, 0.0893164])

In [89]:
# alculating rotation matrix
def rotation_vp2(a,b):
    a_b_sum = a + b
    R = 2*(a_b_sum @ (a_b_sum.T))/(a_b_sum.T @ a_b_sum) - np.identity(len(a))
    return R

a = np.array([1,1,1])
b = np.array([0,0,1])

R = rotation_vp2(a,b)
R @ b

array([2., 2., 1.])

In [94]:
# alculating rotation matrix
# https://math.stackexchange.com/questions/180418/calculate-rotation-matrix-to-align-vector-a-to-vector-b-in-3d (1st algorithm)
def rotation_vp3(a,b):
    a = a/np.linalg.norm(a)
    b = b/np.linalg.norm(b)
    
    v = np.cross(a,b)
    s = np.linalg.norm(v)
    c = np.dot(a,b)
    
    v_matrix = np.array([
        [0, -v[2] , v[1]],
        [v[2], 0, -v[0]],
        [-v[1], v[0], 0]
    ])
    
    v_matrix_squared = v_matrix @ v_matrix
    
    R = np.identity(len(a)) + v_matrix + v_matrix_squared * (1/(1+c))
    
    return R

a = np.array([1,1,1])
b = np.array([0,1,0])
a = a/np.linalg.norm(a)
b = b/np.linalg.norm(b)

R = rotation_vp3(a,b)
print(R @ a)

[-9.71445147e-17  1.00000000e+00 -1.11022302e-16]


In [ ]:
#find the direction of a line

In [139]:
def calculate_normal_vector(p1,p2,p3):
    A = p2 - p1
    A = A/np.linalg.norm(A)
    B = p3 - p1
    B = B/np.linalg.norm(B)

    normal = np.cross(A,B)
    normal = normal/np.linalg.norm(normal)
    return normal

#now need to find the rotation needed
def rotation_vp3(a,b):
    a = a/np.linalg.norm(a)
    b = b/np.linalg.norm(b)
    
    if np.dot(a,b) == 1 or np.dot(a,b) == -1:
        return np.identity(len(a))
    
    print("a.shape = " + str(a.shape))
    print("b.shape = " + str(b.shape))
    
    v = np.cross(a,b)
    s = np.linalg.norm(v)
    c = np.dot(a,b)
    
    v_matrix = np.array([
        [0, -v[2] , v[1]],
        [v[2], 0, -v[0]],
        [-v[1], v[0], 0]
    ])
    
    v_matrix_squared = v_matrix @ v_matrix
    
    R = np.identity(len(a)) + v_matrix + v_matrix_squared * (1/(1+c))
    
    return R

b = np.array([0,0,0])
a = np.array([5,5,5])

direction_of_line = b - a
direction_of_line = direction_of_line/np.linalg.norm(direction_of_line)
print("direction_of_line = " + str(direction_of_line))
print("direction_of_line = " + str(direction_of_line.shape))

# normal vector is just the cross product of 2 lines on the traingle
p1 = np.array([0,1,1])
p2 = np.array([0,1,-1])
p3 = np.array([0,-1,1])

normal = calculate_normal_vector(p1,p2,p3)

print("normal = " + str(normal))
print("normal = " + str(normal.shape))

rotation_matrix_for_normal = rotation_vp3(normal,direction_of_line)

#prove that it correctly rotates the normal vector
print("rotation_matrix_for_normal @ normal = " + str(rotation_matrix_for_normal @ normal))

#rotate the points and then calculate rotation matrix 
p1_rot = rotation_matrix_for_normal @ p1
p2_rot = rotation_matrix_for_normal @ p2
p3_rot = rotation_matrix_for_normal @ p3

#calculate the normal
rotated_normal = calculate_normal_vector(p1_rot,p2_rot,p3_rot)
print("New rotated_normal = " + str(rotated_normal))



direction_of_line = [-0.57735027 -0.57735027 -0.57735027]
direction_of_line = (3,)
normal = [-1. -0. -0.]
normal = (3,)
a.shape = (3,)
b.shape = (3,)
rotation_matrix_for_normal @ normal = [-0.57735027 -0.57735027 -0.57735027]
New rotated_normal = [-0.57735027 -0.57735027 -0.57735027]


# How the synapses are made (previous work):

In [ ]:
def get_synapse_mesh_and_errored_faces(primary_key,return_faces_to_color=True):
    synapse_data_fetched,synapses_already_excluded = get_synapses_with_exclude_list(primary_key["segment_id"])
    
    # 1)Iterate through all synapses:
    # - send the center to the box maker function and save in list
    # - if in the synapse exclude table then save the face numbers in a list 

    face_count = 0
    faces_to_color = []
    synapse_vertices = []
    synapse_faces = []

    for i,syn in enumerate(synapse_data_fetched):
    #     if i < 5:
    #         print(syn["synapse_id"])
        center = (syn["centroid_x"],syn["centroid_y"],syn["centroid_z"])
        center = center*np.array([4, 4, 40])
        side_length = 300
        unit_box_vertices,unit_box_faces = create_synapse_box(center,side_length)
        #add them to the list
        synapse_vertices.append(unit_box_vertices)
        synapse_faces.append(unit_box_faces)

        #check if synapse in already excluded list
        syn_id = syn["synapse_id"]
        if syn_id in synapses_already_excluded:
            #added the faces to color list
            #print(i)
            faces_to_exclude = list(range(face_count,face_count + len(unit_box_faces)))
            #print(faces_to_exclude)
            faces_to_color = faces_to_color + faces_to_exclude

        face_count += len(unit_box_faces)

    print(faces_to_color)
    # 2) Use the mesh concatenation to put all the faces together
    box_mesh_verts, box_mesh_faces = add_mesh_piece(synapse_vertices[0],synapse_faces[0],synapse_vertices[1:],synapse_faces[1:])
    
    return box_mesh_verts,box_mesh_faces,faces_to_color

In [ ]:
"""
Goes through and makes the object and adds the colors:

"""

mymesh = bpy.data.meshes.new("synapse-"+ID)
mymesh.from_pydata(box_mesh_verts.astype(dtype=np.int32).tolist(), [], box_mesh_faces.astype(dtype=np.int32).tolist())
mymesh.update(calc_edges=True)
mymesh.calc_normals()

object = bpy.data.objects.new("synapse-"+ID, mymesh)
#object.location = bpy.context.scene.cursor_location
object.location = Vector((0,0,0))
bpy.context.scene.objects.link(object)


object.lock_location[0] = True
object.lock_location[1] = True
object.lock_location[2] = True
object.lock_scale[0] = True
object.lock_scale[1] = True
object.lock_scale[2] = True

#rotate the z direction by 90 degrees so point correct way

#object.rotation_euler[2] = 1.5708


object.rotation_euler[0] = 4.7124
object.rotation_euler[1] = 0
object.rotation_euler[2] = 0




object.lock_rotation[0] = True
object.lock_rotation[1] = True
object.lock_rotation[2] = True

#run the setup color command
#bpy.ops.object.select_all(action='TOGGLE')
create_local_colors(object)


#then how to label the synapses: 
#print(len(active_edges_raw))

error_label = 10
active_label = 15
faces_raw = object.data.polygons

for i,k in enumerate(faces_raw):
    if i in faces_to_color:
        k.material_index = int(error_label)
    else:
        k.material_index = int(active_label)